### PR TITLE
fix: bug with one character math

### LINKED ISSUE #101: bug with one-character inline math
Reported by @xtimbeau via https://github.com/ropensci-review-tools/babeldown/issues/60 and related discussions

I'll try to fix it.

### PR DESCRIPTION
**Pull request by maelle**
Fix #101 

To be rebased after #102 is merged

### CODE REVIEW

**Comment by maelle** [comment]
@zkamvar no hurry whatsoever (and no review needed if you tell me to just go for it :cowboy_hat_face:), we'll use the branch in babeldown for now.

File: R/asis-nodes.R [hunk 1]
```diff
@@ -52,7 +52,7 @@ inline_dollars_regex <- function(type = c("start", "stop", "full")) {
   # they do not consume the string
   # (https://junli.netlify.app/en/overlapping-regular-expression-in-python/)
   #
-  # This looks for a potetial minus sign followed by maybe a space to allow for
+  # This looks for a potential minus sign followed by maybe a space to allow for
```
Comment (zkamvar) [inline R/asis-nodes.R:55]: 🙈

File: R/asis-nodes.R [hunk 2]
```diff
@@ -64,7 +64,7 @@ inline_dollars_regex <- function(type = c("start", "stop", "full")) {
   switch(type,
     start = start,
     stop = stop,
-    full = glue::glue('({start}.+?{stop})')
+    full = glue::glue('({start}.*?{stop})')
```
Comment (zkamvar) [inline R/asis-nodes.R:67]: OHHH I see what's happening here 👀 😮 

The `{start}` is actually including the first character because it matches any non-punctuation or space after the delimiter, so it must match a math symbol with a single character. Good catch 💯

**Review by zkamvar — APPROVED** [review]
Thank you for this! You may merge at will.
