### PR TITLE
Fix 53

### LINKED ISSUE #53: BUG: numeric chunk options are accidentally quoted
If you specify a chunk option with a numeric input such as `fig.width=4.2`, it becomes quoted on output, which causes knitr to error:

``` r
library(tinkr)
f <- tempfile()
writeLines("```{r ggplot, fig.width=4.2}\n# code here\n```", f)
yarn$new(f)$show()
#> ```{r ggplot, fig.width="4.2"}
#> # code here
#> ```
```

<sup>Created on 2021-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Interestingly enough, this is a problem on the md -> XML side, not on the XML -> md side. 

For example, here is the boomer result of `transform_params()`:

````r
> library(boomer)
> devtools::load_all()                                                                                  
ℹ Loading tinkr

> rig_in_namespace(transform_params)                                                                    

> f <- tempfile() 
  writeLines("```{r ggplot, fig.width=8.8}\n# code here\n```", f) 
  yarn$new(f)$show()                                                                                    
👇 transform_params
💣 try(eval(parse(text = paste("alist(", quote_label(params), ")"))),... 
· 💣 eval(parse(text = paste("alist(", quote_label(params), ")"))) 
· · 💣 parse(text = paste("alist(", quote_label(params), ")")) 
· · · 💣 paste("alist(", quote_label(params), ")") 
· · · · params :
· · · · [1] "r ggplot, fig.width=8.8"
· · · · 💣 💥 quote_label(params) 
· · · · [1] "'r ggplot', fig.width=8.8"
· · · · 
· · · 💥 paste("alist(", quote_label(params), ")") 
· · · [1] "alist( 'r ggplot', fig.width=8.8 )"
· · · 
· · 💥 parse(text = paste("alist(", quote_label(params), ")")) 
· · expression(alist( 'r ggplot', fig.width=8.8 ))
· · 
· 💥 eval(parse(text = paste("alist(", quote_label(params), ")"))) 
· [[1]]
· [1] "r ggplot"
· 
· $fig.width
· [1] 8.8
· 
· 
💥 try(eval(parse(text = paste("alist(", quote_label(params), ")"))),
     silent = TRUE
   ) 
[[1]]
[1] "r ggplot"

$fig.width
[1] 8.8


💣 if (inherits(params_string, "try-error")) {... 
· 💣 💥 inherits(params_string, "try-error") 
· [1] FALSE
· 
💥 if (inherits(params_string, "try-error")) {
     params <- stringr::str_replace(params, " ", ", ")
     params_string <- eval(parse(text = paste(
       "alist(", quote_label(params),
       ")"
     )))
   } 
NULL

💣 parse_label(params_string[[1]]) 
· 💣 💥 params_string[[1]] 
· [1] "r ggplot"
· 
💥 parse_label(params_string[[1]]) 
$language
[1] "r"

$name
[1] "ggplot"


💣 unlist(c(label, params_string[-1])) 
· 💣 c(label, params_string[-1]) 
· · 💣 params_string[-1] 
· · · 💣 💥 -1 
· · · [1] -1
· · · 
· · 💥 params_string[-1] 
· · $fig.width
· · [1] 8.8
· · 
· · 
· 💥 c(label, params_string[-1]) 
· $language
· [1] "r"
· 
· $name
· [1] "ggplot"
· 
· $fig.width
· [1] 8.8
· 
· 
💥 unlist(c(label, params_string[-1])) 
 language      name fig.width 
      "r"  "ggplot"     "8.8" 

· 💣 result[purrr::map_lgl(result, is.character) & !names(result) %in%... 
· · 💣 purrr::map_lgl(result, is.character) & !names(result) %in% c(... 
· · · · 💣 .f(.x[[i]], ...) 
· · · · 💥 .f(.x[[i]], ...) 
· · · · [1] TRUE
· · · · 
· · · · 💣 .f(.x[[i]], ...) 
· · · · 💥 .f(.x[[i]], ...) 
· · · · [1] TRUE
· · · · 
· · · · 💣 .f(.x[[i]], ...) 
· · · · 💥 .f(.x[[i]], ...) 
· · · · [1] TRUE
· · · · 
· · · 💣 💥 purrr::map_lgl(result, is.character) 
· · ·  language      name fig.width 
· · ·      TRUE      TRUE      TRUE 
· · · 
· · · 💣 !names(result) %in% c("language", "name") 
· · · · 💣 names(result) %in% c("language", "name") 
· · · · · 💣 💥 names(result) 
· · · · · [1] "language"  "name"      "fig.width"
· · · · · 
· · · · · 💣 💥 c("language", "name") 
· · · · · [1] "language" "name"    
· · · · · 
· · · · 💥 names(result) %in% c("language", "name") 
· · · · [1]  TRUE  TRUE FALSE
· · · · 
· · · 💥 !names(result) %in% c("language", "name") 
· · · [1] FALSE FALSE  TRUE
· · · 
· · 💥 purrr::map_lgl(result, is.character) & !names(result) %in% c(
· ·      "language",
· ·      "name"
· ·    ) 
· ·  language      name fig.width 
· ·     FALSE     FALSE      TRUE 
· · 
· 💥 result[purrr::map_lgl(result, is.character) & !names(result) %in%
·      c("language", "name")] 
· fig.width 
·     "8.8" 
· 
💣 💥 glue::glue("\"{result[purrr::map_lgl(result, is.character)&\n           !names(result) %in% c(\"language\", \"name\")]}\"") 
"8.8"

💣 purrr::map_lgl(result, is.character) & !names(result) %in% c(... 
· · 💣 .f(.x[[i]], ...) 
· · 💥 .f(.x[[i]], ...) 
· · [1] TRUE
· · 
· · 💣 .f(.x[[i]], ...) 
· · 💥 .f(.x[[i]], ...) 
· · [1] TRUE
· · 
· · 💣 .f(.x[[i]], ...) 
· · 💥 .f(.x[[i]], ...) 
· · [1] TRUE
· · 
· 💣 💥 purrr::map_lgl(result, is.character) 
·  language      name fig.width 
·      TRUE      TRUE      TRUE 
· 
· 💣 !names(result) %in% c("language", "name") 
· · 💣 names(result) %in% c("language", "name") 
· · · 💣 💥 names(result) 
· · · [1] "language"  "name"      "fig.width"
· · · 
· · · 💣 💥 c("language", "name") 
· · · [1] "language" "name"    
· · · 
· · 💥 names(result) %in% c("language", "name") 
· · [1]  TRUE  TRUE FALSE
· · 
· 💥 !names(result) %in% c("language", "name") 
· [1] FALSE FALSE  TRUE
· 
💥 purrr::map_lgl(result, is.character) & !names(result) %in% c(
     "language",
     "name"
   ) 
 language      name fig.width 
    FALSE     FALSE      TRUE 

💣 💥 c(
        "echo", "eval", "collapse", "warning", "error", "message",
        "split", "include", "strip.white", "prompt", "highlight",
        "cache", "autodep", "external", "sanitize", "purl"
      ) 
 [1] "echo"        "eval"        "collapse"    "warning"     "error"       "message"     "split"      
 [8] "include"     "strip.white" "prompt"      "highlight"   "cache"       "autodep"     "external"   
[15] "sanitize"    "purl"       

💣 if (any(names(result) %in% logical_options)) {... 
· 💣 any(names(result) %in% logical_options) 
· · 💣 names(result) %in% logical_options 
· · · 💣 💥 names(result) 
· · · [1] "language"  "name"      "fig.width"
· · · 
· · 💥 names(result) %in% logical_options 
· · [1] FALSE FALSE FALSE
· · 
· 💥 any(names(result) %in% logical_options) 
· [1] FALSE
· 
💥 if (any(names(result) %in% logical_options)) {
     result[names(result) %in% logical_options & is.character(result)] <- stringr::str_remove_all(result[names(result) %in%
       logical_options & is.character(result)], "\\\"")
   } 
NULL

👆 transform_params
```{r ggplot, fig.width="8.8"}
# code here
```

````

### PR DESCRIPTION
**Pull request by zkamvar**
I've modified `transform_params()` in the following ways:

1. assigned the subsetting statements to descriptive names
2. disallowed logical params from being quoted in the first place
3. protected fig.width and fig.height from being quoted
4. replaced the {glue} statement with the equivalent `shQuote(var, type = "cmd")`

reprex:

``` r
library(tinkr)
f <- tempfile()
writeLines("```{r ggplot, fig.width=4.2}\n# code here\n```", f)
yarn$new(f)$show()
#> ```{r ggplot, fig.width=4.2}
#> # code here
#> ```
```

<sup>Created on 2021-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This will fix #53

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -61,33 +61,27 @@ transform_params <- function(params){
   params_string <- try(eval(parse(text = paste('alist(', quote_label(params), ')'))),
                        silent = TRUE)
 
-  if(inherits(params_string, "try-error")){
+  if (inherits(params_string, "try-error")){
```
Comment (maelle) [inline R/utils.R:64]:
```suggestion
  if (inherits(params_string, "try-error")) {
```

Even more whitespace :grin:

File: R/utils.R [hunk 2]
```diff
@@ -61,33 +61,27 @@ transform_params <- function(params){
...
 
   label <- parse_label(params_string[[1]])
 
   result <- unlist(c(label, params_string[-1]))
-  result[purrr::map_lgl(result, is.character)&
-           !names(result) %in% c("language", "name")] <- glue::glue('"{result[purrr::map_lgl(result, is.character)&
-           !names(result) %in% c("language", "name")]}"')
 
-  logical_options <- c("echo", "eval", "collapse", "warning",
+  logical_options  <- c("echo", "eval", "collapse", "warning",
```
Comment (maelle) [inline R/utils.R:73]:
```suggestion
  logical_options <- c("echo", "eval", "collapse", "warning",
```

**Review by maelle — APPROVED** [review]
Thank you for catching and fixing this!

I only wonder whether we should add two options for letting users grow the list of unquoted and logical parameters (in case they are dealing with documents where they defined and use parameters)? Or [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)*?

*: phrase I learnt last week. :sweat_smile:

**Comment by zkamvar** [comment]
> I only wonder whether we should add two options for letting users grow the list of unquoted and logical parameters (in case they are dealing with documents where they defined and use parameters)? Or YAGNI*?

I'm actually thinking that we could simplify this a bit more. We only need to check for character arguments so that we can add an extra layer of quotes. Instead of explicitly creating a list of params to _not_ quote, we could map over the initial list (before unlisting) and find the characters that need quoting. I'll add another commit for this.

File: R/utils.R (hunk 1 above)
Comment (zkamvar) [reply R/utils.R]: good catch!

**Comment by zkamvar** [comment]
Because I changed a part of the code that was not previously covered by tests and now that I changed it, codecov is complaining because this line is not being covered :weary: It would be good to get this line covered. Do you know what situation we would run into this? it seems to be a missing comma issue, but I'm unsure of how to trigger it.

**Comment by maelle** [comment]
sorry which line is that exactly? I think I'm not looking at the right thing.

**Comment by zkamvar** [comment]
> sorry which line is that exactly? I think I'm not looking at the right thing.

It's line 67 which is only run if the first pass through parsing params fails: https://github.com/ropensci/tinkr/pull/54/files#diff-60bef5af43a1bd541299ce9bceeb226afb23deaa5e637b145c85e05ffd552b0cR67

**Comment by maelle** [comment]
mmmh, fine to ignore?

**Comment by zkamvar** [comment]
> mmmh, fine to ignore?

I think so. In the future, it would be good to revisit this to figure out what situations would cause this block to be called.
